version:  '3.1'

services :

  db:

    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: strong_password
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  adminer:

    image: adminer
    restart: always
    ports:
      - 8080:8080    
    depends_on:
      - db

  etl:

    image: etl
    restart: always
    depends_on: 
      - db    

volumes:
  postgres_data:
    driver: local
         